# Generated by Django 4.1.7 on 2023-03-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('moves', models.TextField()),
                ('eco_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChessPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=1)),
                ('piece_type', models.CharField(choices=[('K', 'King'), ('Q', 'Queen'), ('R', 'Rook'), ('B', 'Bishop'), ('N', 'Knight'), ('P', 'Pawn')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ChessResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('result_type', models.CharField(max_length=10)),
            ],
        ),
    ]
