# Generated by Django 4.1.7 on 2023-03-21 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0004_remove_chessopening_variation_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('moves', models.TextField(blank=True, null=True)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='OpeningAnalysis.chessopening')),
            ],
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
