# Generated by Django 4.1.6 on 2023-03-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0006_chessopeningimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessopeningimage',
            name='opening',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='OpeningAnalysis.chessopening'),
        ),
    ]
