# Generated by Django 4.1.6 on 2023-03-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0007_chessopeningimage_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessopeningimage',
            name='opening',
        ),
        migrations.AddField(
            model_name='chessopeningimage',
            name='openings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='OpeningAnalysis.chessopening'),
        ),
    ]
