# Generated by Django 4.1.6 on 2023-03-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0008_remove_chessopeningimage_opening_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessopeningimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
