# Generated by Django 4.1.7 on 2023-03-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0009_alter_chessopeningimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningAnalysisImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
