# Generated by Django 4.1.7 on 2023-03-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0010_openinganalysisimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openinganalysisimage',
            old_name='image',
            new_name='analysisImage',
        ),
    ]
