# Generated by Django 4.1.7 on 2023-03-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0011_rename_image_openinganalysisimage_analysisimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningAnalysisImage',
        ),
    ]
