# Generated by Django 4.1.7 on 2023-03-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpeningAnalysis', '0012_delete_openinganalysisimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, upload_to='image')),
            ],
        ),
    ]
